### ISSUE TITLE
home-page metadata without http:// or https:// prefix gets 400 from pypi

### ISSUE THREAD

**Issue by mpacer** [takluyver/flit#103]
```
Traceback (most recent call last):
  File "~/anaconda3/envs/dev/bin/flit", line 11, in <module>
    sys.exit(main())
  File "~/anaconda3/envs/dev/lib/python3.5/site-packages/flit/__init__.py", line 88, in main
    repo=args.repository)
  File "~/anaconda3/envs/dev/lib/python3.5/site-packages/flit/wheel.py", line 210, in wheel_main
    do_upload(wheel_path, wb.metadata, repo)
  File "~/anaconda3/envs/dev/lib/python3.5/site-packages/flit/upload.py", line 164, in do_upload
    upload_wheel(file, metadata, repo)
  File "~/anaconda3/envs/dev/lib/python3.5/site-packages/flit/upload.py", line 133, in upload_wheel
    resp.raise_for_status()
  File "~/anaconda3/envs/dev/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: home_page: Invalid URI for url: https://upload.pypi.io/legacy/
```

This was fixed by changing 

```python
home-page:michaelpacer.com
```

to 
```python
home-page:https://michaelpacer.com
```

when (on its own…as of the time of this writing https://michaelpacer.com doesn't even resolve correctly because of some DNS issues), which makes me think that this is being caught by pypi's metadata parser as opposed to an actual call to the site. That makes me think it might be possible to catch these errors by mimicking that parsing mechanism. Otherwise, catching the error as a 400 response from https://upload.pypi.io/legacy isn't too informative as to what needs to be fixed.

**Comment by takluyver** [comment]
Yep, it would make sense to validate that before trying to upload. I think I've found the code in PyPI that checks it, if anyone wants to dig in to what it's doing:

https://github.com/pypa/pypi-legacy/blob/15d875361d0dd555cc25acb28ec839c3dba637db/webui.py#L2700
