### ISSUE TITLE
ReadMeHTMLTranslator error on README.rST file containing images

### ISSUE THREAD

**Issue by Naereen** [takluyver/flit#111]
No matter how I try, I cannot succeed to use flit with [this README.rst](https://github.com/Naereen/Lempel-Ziv_Complexity/blob/master/README.rst) file, and the issue comes from the images.
The file is a valid rST file, as shown by GitHub displaying it, and [readme_renderer](https://pypi.python.org/pypi/readme_renderer) test succeeding.

Flit fails with the following error:
```bash
$ flit sdist
self = <flit.vendorized.readme.rst.ReadMeHTMLTranslator object at 0x7f9e513b4a90>
self.context = ['</p>\n']
node = <image alt="PyPI version" uri="https://img.shields.io/pypi/v/lempel_ziv_complexity.png"/>
Traceback (most recent call last):
  File "/usr/local/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/flit/__init__.py", line 114, in main
    SdistBuilder(args.ini_file).build()
  File "/usr/local/lib/python3.5/dist-packages/flit/sdist.py", line 131, in __init__
    self.ini_info = inifile.read_pkg_ini(ini_path)
  File "/usr/local/lib/python3.5/dist-packages/flit/inifile.py", line 114, in read_pkg_ini
    return _validate_config(cp, path)
  File "/usr/local/lib/python3.5/dist-packages/flit/inifile.py", line 159, in _validate_config
    _, ok = render(raw_desc, stream)
  File "/usr/local/lib/python3.5/dist-packages/flit/vendorized/readme/rst.py", line 120, in render
    parts = publish_parts(raw, writer=writer, settings_overrides=settings)
  File "/usr/local/lib/python3.5/dist-packages/docutils/core.py", line 448, in publish_parts
    enable_exit_status=enable_exit_status)
  File "/usr/local/lib/python3.5/dist-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/local/lib/python3.5/dist-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/usr/local/lib/python3.5/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/local/lib/python3.5/dist-packages/docutils/writers/_html_base.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/usr/local/lib/python3.5/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.5/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.5/dist-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/local/lib/python3.5/dist-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/usr/local/lib/python3.5/dist-packages/docutils/writers/html4css1/__init__.py", line 658, in depart_paragraph
    self.body.append(self.context.pop())
IndexError: pop from empty list
```
I added the first line to check, apparently your [`depart_image`](https://github.com/takluyver/flit/blob/master/flit/vendorized/readme/rst.py#L48) distutil command is closing the context (`self.context.pop()`) too early (I am not an expert in distutil HTML translator, so I don't know exactly how it does it)

Thanks in advance.

**Comment by Naereen** [comment]
Also, flit fails if the current directory is not a VCS ?! Why?

It seems fair to force to have no un-commited files or a durty VCS state, but completely inappropriate to force to be in a VCS...

**Comment by Naereen** [comment]
After removing the images from my README.rst files, of course the upload worked perfectly well:
https://pypi.org/project/Lempel-Ziv_Complexity/#description

So thanks and :clap: for flit!

**Comment by takluyver** [comment]
I cloned the repo and tried it, and it seems to be fine with the README on my machine. :confused: If there's a bug in docutils, there's not much I can do besides adding some way to skip the rendering check.

The VCS requirement is only for building sdists - you can build wheels or install the package without it being in a VCS. It's a bit of an awkward compromise, but we use the VCS to define which files to include in the sdist. I'm very keen to avoid something like `MANIFEST.in` defining which files go into the sdist.

I've just noticed that it fails to identify that the parent directory is a git repo, though. That's a bug.

**Comment by takluyver** [comment]
a3b092da0b3ee779b5dbb81cc3fe996adbf759fb should fix the issue where it can't identify that the CWD is inside a git repo.

**Comment by Naereen** [comment]
Hi, thanks for your quick reply.

- OK for the VCS detection (and the bugfix) part,
- Not so important if it bugs only on my machine.. Don't worry about it.
- But if someone else reports a bug related to images and this `self.context.pop` issue, we will have to solve it :wink: !

**Comment by takluyver** [comment]
Aha, it looks like I was on an old version of docutils; when I upgrade to docutils 0.13.1, or 0.14rc1, I do see it.

**Comment by takluyver** [comment]
Should be fixed now - can you try with master? If that works for you, I'll make a quick release.

**Comment by Naereen** [comment]
Trying...

**Comment by Naereen** [comment]
Seems fine now.

**Comment by takluyver** [comment]
Thanks :-). I'll make a release with the fix.

**Comment by takluyver** [comment]
And done
