### ISSUE TITLE
flit don't like when module don't have __version__

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#12]
```
$ flit wheel
Traceback (most recent call last):
  File "/usr/local/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/Users/bussonniermatthias/Library/Python/3.5/lib/python/site-packages/flit/__init__.py", line 57, in main
    verify_metadata=args.verify_metadata).build()
  File "/Users/bussonniermatthias/Library/Python/3.5/lib/python/site-packages/flit/wheel.py", line 31, in __init__
    self.metadata = common.make_metadata(self.module, self.ini_info)
  File "/Users/bussonniermatthias/Library/Python/3.5/lib/python/site-packages/flit/common.py", line 148, in make_metadata
    md_dict.update(get_info_from_module(module))
  File "/Users/bussonniermatthias/Library/Python/3.5/lib/python/site-packages/flit/common.py", line 40, in get_info_from_module
    'version': m.__version__}
AttributeError: module 'roman_count' has no attribute '__version__'
```

**Comment by Carreau** [comment]
closed by #16
