### ISSUE TITLE
Can't use flit on Windows because UnicodeEncodeError

### ISSUE THREAD

**Issue by mlouielu** [takluyver/flit#120]
I try `flit build` on Windows, and got this result. 

```
%PYTHON%\python.exe -m flit build
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\site-packages\flit\__main__.py", line 5, in <module>
    main()
  File "C:\Python34\lib\site-packages\flit\__init__.py", line 120, in main
    main(args.ini_file, formats=set(args.format or []))
  File "C:\Python34\lib\site-packages\flit\build.py", line 21, in main
    wheel_info = wheel_main(ini_file)
  File "C:\Python34\lib\site-packages\flit\wheel.py", line 203, in wheel_main
    wb = WheelBuilder(ini_path, fp)
  File "C:\Python34\lib\site-packages\flit\wheel.py", line 44, in __init__
    self.ini_info = inifile.read_pkg_ini(ini_path)
  File "C:\Python34\lib\site-packages\flit\inifile.py", line 114, in read_pkg_ini
    return _validate_config(cp, path)
  File "C:\Python34\lib\site-packages\flit\inifile.py", line 150, in _validate_config
    raw_desc =  f.read()
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 669: character maps to <undefined>
```

**Comment by takluyver** [comment]
Thanks for the report!

**Comment by mlouielu** [comment]
@takluyver My pleasure. Thanks for your great project, it saves my life.

**Comment by takluyver** [comment]
:-)
