### ISSUE TITLE
Can I publish to testpypi using flit?

### ISSUE THREAD

**Issue by Mariatta** [takluyver/flit#122]
I was looking for instruction on how to publish to testPyPI using `flit` but couldn't find it:
http://flit.readthedocs.io/en/latest/search.html?q=testpypi&check_keywords=yes&area=default

Is this supported? 
Thanks :smile:

**Comment by takluyver** [comment]
If you have testpypi set up in your `.pypirc` file like this:

```
[distutils]
index-servers =
    pypi
    testpypi

[pypi]
repository: https://upload.pypi.org/legacy/
username: takowl

[testpypi]
repository: https://test.pypi.org/legacy/
username: takluyver
```

Then you should be able to upload to it with `flit --repository testpypi publish`.

**Comment by takluyver** [comment]
I'll leave this open for now because it could be better documented, and I'm considering whether we should support `testpypi` as a repository without the user needing to configure their .pypirc manually.

**Comment by Carreau** [comment]
> and I'm considering whether we should support testpypi as a repository without the user needing to configure their .pypirc manually.

Well you have to as you need to create an account on testpypi right ?

**Comment by takluyver** [comment]
You'd have to create an account, but you wouldn't necessarily have to configure .pypirc by hand.

If you `flit publish` to regular PyPI today without a `.pypirc` file, it will prompt you for your username and password and create the file for you. We could do the same for testpypi.

**Comment by Carreau** [comment]
> If you flit publish to regular PyPI today without a .pypirc file, it will prompt you for your username and password and create the file for you. We could do the same for testpypi.

Ah ! I missunderstood. Yes, that make sesns.

**Comment by Mariatta** [comment]
> I'm considering whether we should support testpypi as a repository without the user needing to configure their .pypirc manually.

Sounds like a great idea! 😄 

> Then you should be able to upload to it with `flit --repository testpypi publish`.

I tried but it's not working 😞 I'm not sure if it's a problem with `flit` or `testpypi`..

This is what I have in my `~/.pypirc`
```
[distutils]
index-servers =
    pypi
    testpypi

[testpypi]
repository = https://test.pypi.org/legacy
username:<myTestPyPIusername>
password:<myTestPyPIpassword>

[pypi]
username:<myPyPIusername>
password:<myPyPIusername>
```

Output
```
$ flit --repository testpypi publish
Copying package file(s) from cherry_picker                                                                                      I-flit.wheel
Writing metadata files                                                                                                          I-flit.wheel
Writing the record of files                                                                                                     I-flit.wheel
Built wheel: dist/cherry_picker-0.1.0.dev1-py3-none-any.whl                                                                     I-flit.wheel
Found 6 files tracked in git                                                                                                    I-flit.sdist
Writing generated setup.py                                                                                                      I-flit.sdist
Built sdist: dist/cherry_picker-0.1.0.dev1.tar.gz                                                                               I-flit.sdist
Using repository at https://test.pypi.org/legacy                                                                               I-flit.upload
Uploading dist/cherry_picker-0.1.0.dev1-py3-none-any.whl...                                                                    I-flit.upload
Traceback (most recent call last):
  File "/Users/Mariatta/python_github/core-workflow/venv/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/Users/Mariatta/python_github/core-workflow/venv/lib/python3.6/site-packages/flit/__init__.py", line 123, in main
    main(args.ini_file, args.repository, formats=set(args.format or []))
  File "/Users/Mariatta/python_github/core-workflow/venv/lib/python3.6/site-packages/flit/upload.py", line 288, in main
    do_upload(built.wheel.file, built.wheel.builder.metadata, repo_name)
  File "/Users/Mariatta/python_github/core-workflow/venv/lib/python3.6/site-packages/flit/upload.py", line 261, in do_upload
    upload_file(file, metadata, repo)
  File "/Users/Mariatta/python_github/core-workflow/venv/lib/python3.6/site-packages/flit/upload.py", line 230, in upload_file
    resp.raise_for_status()
  File "/Users/Mariatta/python_github/core-workflow/venv/lib/python3.6/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://test.pypi.org/legacy/
```

**Comment by mlouielu** [comment]
@Mariatta You lost the `/` at the end of your URL.

I can upload successfully to testpypi for my package:
```
➜  twstock git:(master) flit --repository testpypi publish
Copying package file(s) from twstock                                                                                                                        I-flit.wheel
Writing metadata files                                                                                                                                      I-flit.wheel
Writing the record of files                                                                                                                                 I-flit.wheel
Built wheel: dist/twstock-1.0.1-py3-none-any.whl                                                                                                            I-flit.wheel
Found 46 files tracked in git                                                                                                                               I-flit.sdist
Writing generated setup.py                                                                                                                                  I-flit.sdist
Built sdist: dist/twstock-1.0.1.tar.gz                                                                                                                      I-flit.sdist
Using repository at https://test.pypi.org/legacy/                                                                                                          I-flit.upload
Uploading dist/twstock-1.0.1-py3-none-any.whl...                                                                                                           I-flit.upload
Package is at https://test.pypi.org/project/twstock/                                                                                                       I-flit.upload
Using repository at https://test.pypi.org/legacy/                                                                                                          I-flit.upload
Uploading dist/twstock-1.0.1.tar.gz...                                                                                                                     I-flit.upload
Package is at https://test.pypi.org/project/twstock/                                                                                                       I-flit.upload
```


But failed when lost the `/`:
```
Uploading dist/twstock-1.0.1-py3-none-any.whl...                                                                                                           I-flit.upload
Traceback (most recent call last):
  File "/usr/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/home/grd/.local/lib/python3.6/site-packages/flit/__init__.py", line 123, in main
    main(args.ini_file, args.repository, formats=set(args.format or []))
  File "/home/grd/.local/lib/python3.6/site-packages/flit/upload.py", line 288, in main
    do_upload(built.wheel.file, built.wheel.builder.metadata, repo_name)
  File "/home/grd/.local/lib/python3.6/site-packages/flit/upload.py", line 261, in do_upload
    upload_file(file, metadata, repo)
  File "/home/grd/.local/lib/python3.6/site-packages/flit/upload.py", line 230, in upload_file
    resp.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://test.pypi.org/legacy/
```

**Comment by Mariatta** [comment]
Thanks @mlouielu That works!
So it's user error after all 😅 

If `flit` can take care of this so users like me don't make mistakes with `~/.pypirc` then it would be great 😊
