### ISSUE TITLE
Don't require home-page to install package

### ISSUE THREAD

**Issue by brycepg** [takluyver/flit#173]
The `home-page` field isn't really 'required' for installation, yet flit seems to think it is:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/flit/__init__.py", line 110, in main
    symlink=args.symlink, deps=args.deps, pth=args.pth_file).install()
  File "/home/user/.local/lib/python3.6/site-packages/flit/install.py", line 99, in __init__
    self.ini_info = inifile.read_pkg_ini(ini_path)
  File "/home/user/.local/lib/python3.6/site-packages/flit/inifile.py", line 53, in read_pkg_ini
    res = prep_toml_config(d, path)
  File "/home/user/.local/lib/python3.6/site-packages/flit/inifile.py", line 90, in prep_toml_config
    md_dict, module = _prep_metadata(d['metadata'], path)
  File "/home/user/.local/lib/python3.6/site-packages/flit/inifile.py", line 176, in _prep_metadata
    raise ConfigError("Required fields missing: " + '\n'.join(missing))
flit.inifile.ConfigError: Required fields missing: home-page
```

**Comment by merwok** [comment]
`flit init` still requires some value for the home page.

Should I open a new ticket?
