### ISSUE TITLE
Don't print a traceback when flit knows the mistake of the user

### ISSUE THREAD

**Issue by pradyunsg** [takluyver/flit#174]
I just tried to build a package and got a Traceback because I hadn't added a docstring.

It would have been nicer to just have gotten an error message on stderr, instead of a full traceback.

Currently:
```
$ flit build
Traceback (most recent call last):
  File "/Users/pradyunsg/.venvwrap/venvs/flit-trial/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/Users/pradyunsg/.venvwrap/venvs/flit-trial/lib/python3.6/site-packages/flit/__init__.py", line 101, in main
    main(args.ini_file, formats=set(args.format or []))
  File "/Users/pradyunsg/.venvwrap/venvs/flit-trial/lib/python3.6/site-packages/flit/build.py", line 40, in main
    sb = SdistBuilder(ini_file)
  File "/Users/pradyunsg/.venvwrap/venvs/flit-trial/lib/python3.6/site-packages/flit/sdist.py", line 153, in __init__
    self.metadata = common.make_metadata(self.module, self.ini_info)
  File "/Users/pradyunsg/.venvwrap/venvs/flit-trial/lib/python3.6/site-packages/flit/common.py", line 294, in make_metadata
    md_dict.update(get_info_from_module(module))
  File "/Users/pradyunsg/.venvwrap/venvs/flit-trial/lib/python3.6/site-packages/flit/common.py", line 114, in get_info_from_module
    raise NoDocstringError('Cannot package module without docstring, or empty docstring. '
flit.common.NoDocstringError: Cannot package module without docstring, or empty docstring. Please add a docstring to your module.
```

I'm proposing:

```
flit cannot package module without docstring, or empty docstring. Please add a docstring to your module.
```

**Comment by takluyver** [comment]
Sounds like a good plan. I think I've done something elsewhere by making the relevant exceptions inherit from a common type called `UserError` or something, and then catching that at the top level.

**Comment by pradyunsg** [comment]
As much as I'd like to, I'll probably not be getting the time to jump in the near future though. :/

Feel free to put a "good first issue" label on these.

**Comment by takluyver** [comment]
Good plan, I've done that.
