### ISSUE TITLE
Invalid or non-existent authentication information

### ISSUE THREAD

**Issue by eliasdabbas** [takluyver/flit#182]
Hello, 

I'm trying to go through the simple example mentioned on the documentation page, I followed the steps exactly. but I'm getting an authentication error. 

I've tried to set FLIT_USERNAME and FLIT_PASSWORD as environment variables, I also tried adding them to my pypirc file. I'm still getting the following error: 

```
> flit publish
Found 4 files tracked in git                                                                                            I-flit.sdist
Writing generated setup.py                                                                                              I-flit.sdist
Built sdist: dist/foobar-0.1.tar.gz                                                                                     I-flit.sdist
Copying package file(s) from /var/folders/fw/9dzb61hs5zschvczk5wmkpj80000gn/T/tmp4xx9qzwx/foobar-0.1/foobar.py          I-flit.wheel
Writing metadata files                                                                                                  I-flit.wheel
Writing the record of files                                                                                             I-flit.wheel
Built wheel: dist/foobar-0.1-py2.py3-none-any.whl                                                                       I-flit.wheel
Using repository at https://upload.pypi.org/legacy/                                                                    I-flit.upload
Uploading dist/foobar-0.1-py2.py3-none-any.whl...                                                                      I-flit.upload
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flit/__init__.py", line 139, in main
    main(args.ini_file, args.repository, formats=set(args.format or []))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flit/upload.py", line 291, in main
    do_upload(built.wheel.file, built.wheel.builder.metadata, repo_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flit/upload.py", line 264, in do_upload
    upload_file(file, metadata, repo)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flit/upload.py", line 233, in upload_file
    resp.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/

```

```
> python --version
Python 3.6.5 :: Anaconda custom (64-bit)
~/flittest/
> flit --version
Flit 0.13
```
Am I doing anything wrong? 

Thanks a lot!

**Comment by eliasdabbas** [comment]
Perfect. That works, and I have the package on PYPI.
Thank you.
