### ISSUE TITLE
flit installfrom fails when project uses pyproject.toml

### ISSUE THREAD

**Issue by jwkvam** [takluyver/flit#215]
For example:
```
flit installfrom github:takluyver/flit
```
I get this:
```
Traceback (most recent call last):
  File "/Users/jacques/miniconda/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/__init__.py", line 127, in main
    sys.exit(installfrom(args.location, user=args.user, python=args.python))
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/installfrom.py", line 123, in installfrom
    return install_local(fetch(*parse_address(address)), user=user, python=python)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/installfrom.py", line 114, in install_local
    deps='production').install()
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/install.py", line 106, in __init__
    self.ini_info = inifile.read_pkg_ini(ini_path)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/inifile.py", line 56, in read_pkg_ini
    cp = _read_pkg_ini(path)
  File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/inifile.py", line 156, in _read_pkg_ini
    with path.open(encoding='utf-8') as f:
  File "/Users/jacques/miniconda/lib/python3.6/pathlib.py", line 1181, in open
    opener=self._opener)
  File "/Users/jacques/miniconda/lib/python3.6/pathlib.py", line 1035, in _opener
    return self._accessor.open(self, flags, mode)
  File "/Users/jacques/miniconda/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/gd/p_8rmvg56j39gd6lnkb7_51h0000gn/T/tmpvkk0bqnq/flit-master/flit.ini'
```

Could we make this a try catch?
https://github.com/takluyver/flit/blob/baac76acace043e3f6c09ae7a51dc2599096ec22/flit/installfrom.py#L113

Well I see that this command is deprecated as of 1.2.1 so maybe this is moot.

**Comment by takluyver** [comment]
Yup, it should check for pyproject.toml first, and then try flit.ini.

The command is deprecated, but I don't know quite when pip will be a viable alternative, so it's definitely in scope to fix something like this. Do you want to make a PR?

**Comment by jwkvam** [comment]
Yea I can try this, probably sometime this week.
