### ISSUE TITLE
Instructions don't work - VCSError

### ISSUE THREAD

**Issue by cdeil** [takluyver/flit#269]
The instructions as given in the README don't work.

Maybe add `git init`?

For the first step it also wasn't obvious to me if I should to `mkdir` and `cd` myself or if `flit` would do that for me.

Update docs a bit to clarify?
Let me know if you want me to send a PR or just do it yourself.

```
(base) hfm-1804a:foobar deil$ conda activate flit
(flit) hfm-1804a:foobar deil$ flit init
Module name [foobar]: 
Author [Christoph Deil]: Sir Robin
Author email [Deil.Christoph@gmail.com]: robin@camelot.uk
Home page [https://github.com/cdeil/foobar]: https://github.com/sirrobin/foobar
Choose a license (see http://choosealicense.com/ for more info)
1. MIT - simple and permissive
2. Apache - explicitly grants patent rights
3. GPL - ensures that code based on this is shared with the same terms
4. Skip - choose a license later
Enter 1-4 [1]: 1

Written pyproject.toml; edit that file to add optional extra info.
(flit) hfm-1804a:foobar deil$ ls -lh
total 24
-rw-r--r--  1 deil  staff   1.1K May 15 14:50 LICENSE
-rw-r--r--  1 deil  staff    54B May 15 14:49 foobar.py
-rw-r--r--  1 deil  staff   269B May 15 14:50 pyproject.toml
(flit) hfm-1804a:foobar deil$ cat pyproject.toml 
[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "foobar"
author = "Sir Robin"
author-email = "robin@camelot.uk"
home-page = "https://github.com/sirrobin/foobar"
classifiers = ["License :: OSI Approved :: MIT License"]

(flit) hfm-1804a:foobar deil$ flit publish
Traceback (most recent call last):
  File "/Users/deil/software/anaconda3/envs/flit/bin/flit", line 10, in <module>
    sys.exit(main())
  File "/Users/deil/software/anaconda3/envs/flit/lib/python3.7/site-packages/flit/__init__.py", line 115, in main
    main(args.ini_file, args.repository, formats=set(args.format or []))
  File "/Users/deil/software/anaconda3/envs/flit/lib/python3.7/site-packages/flit/upload.py", line 267, in main
    built = build.main(ini_path, formats=formats)
  File "/Users/deil/software/anaconda3/envs/flit/lib/python3.7/site-packages/flit/build.py", line 41, in main
    sdist_file = sb.build()
  File "/Users/deil/software/anaconda3/envs/flit/lib/python3.7/site-packages/flit/sdist.py", line 239, in build
    files_to_add = self.find_tracked_files()
  File "/Users/deil/software/anaconda3/envs/flit/lib/python3.7/site-packages/flit/sdist.py", line 174, in find_tracked_files
    vcs_mod = identify_vcs(self.srcdir)
  File "/Users/deil/software/anaconda3/envs/flit/lib/python3.7/site-packages/flit/vcs/__init__.py", line 15, in identify_vcs
    raise VCSError("Directory does not appear to be in a VCS", directory)
flit.common.VCSError: Directory does not appear to be in a VCS (/Users/deil/temp/foobar)
```

**Comment by takluyver** [comment]
Flit 2 doesn't rely on version control - it will still use one if it finds it, but in its absence, it will build an sdist containing the files inside the package, `pyproject.toml` and the description file. You can also include and exclude files from the sdist [via pyproject.toml](https://flit.readthedocs.io/en/latest/pyproject_toml.html#sdist-section).

So hopefully the introductory guide should be working again.
