### ISSUE TITLE
Development guide in README not working

### ISSUE THREAD

**Issue by uranusjr** [takluyver/flit#291]
From the README:

> To install the development version of Flit from Github:
>
> ```
> git clone https://github.com/takluyver/flit.git
> cd flit
> python3 -m pip install docutils requests pytoml
> python3 -m flit install
> ```

First attempt:

```
$ git clone https://github.com/takluyver/flit.git
$ cd flit/
$ python -m pip install docutils requests pytoml
$ python -m flit install
Traceback (most recent call last):
  File "runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "flit/__init__.py", line 9, in <module>
    from flit_core import common
ImportError: cannot import name 'common' from 'flit_core' (unknown location)
```

Second attempt:

```
$ PYTHONPATH=flit_core python -m flit
The file description seems not to be valid rst for PyPI; it will be interpreted as plain text  E-flit.validate
<string>:25: (WARNING/2) Cannot analyze code. Pygments package not found.
                E-flit.validate
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "flit/__main__.py", line 5, in <module>
    main()
  File "flit/__init__.py", line 137, in main
    pth=args.pth_file).install()
  File "flit/install.py", line 106, in __init__
    self.ini_info = inifile.read_flit_config(ini_path)
  File "flit/inifile.py", line 16, in read_flit_config
    raise ConfigError("Invalid config values (see log)")
flit_core.inifile.ConfigError: Invalid config values (see log)
```

Third attempt:

```
$ python -m pip install pygments
$ PYTHONPATH=flit_core python -m flit install
$ flit
Traceback (most recent call last):
  File "flit", line 5, in <module>
    from flit import main
  File "flit/__init__.py", line 9, in <module>
    from flit_core import common
ModuleNotFoundError: No module named 'flit_core'
```

Fourth attempt:

```
# Out of ideas...
$ cp -r flit_core/flit_core $(python -c 'import sysconfig; print(sysconfig.get_path("purelib"))')
$ flit
```

I have no idea what should be done, but the guide is definitely not right 🙂

**Comment by takluyver** [comment]
Yes, sorry, it's all kind of incomplete at the moment. I'm trying to piece together little bits of spare time to get to a vaguely coherent state for Flit 2.
