### ISSUE TITLE
Cannot install from source nor download tarball

### ISSUE THREAD

**Issue by seppeljordan** [takluyver/flit#296]
Hi, I wanted to download the source distributions for the latest flit version.  Instead of downloading the appropriate distributions I encountered the following error:

```
[sebastian@librem:/tmp/tmp.T3P0i9HVs6]$ pip --version
pip 19.3.1 from /tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip (python 3.7)
(.env) 
[sebastian@librem:/tmp/tmp.T3P0i9HVs6]$ pip download flit --no-binary :all:
Collecting flit
  File was already downloaded /tmp/tmp.T3P0i9HVs6/flit-2.0.2.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 2:
   command: /tmp/tmp.T3P0i9HVs6/.env/bin/python3.7 /tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /run/user/1000/pip-build-env-1pf2pow0/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'flit_core >=2.0.2,<3'
       cwd: None
  Complete output (42 lines):
  Collecting flit_core<3,>=2.0.2
    Using cached https://files.pythonhosted.org/packages/89/cf/a76f37dfded167e97936b8d53308abe5a8d00b97d417a6a405e69167e685/flit_core-2.0.2.tar.gz
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
  ERROR: Exception:
  Traceback (most recent call last):
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
      status = self.run(options, args)
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
      resolver.resolve(requirement_set)
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
      self._resolve_one(requirement_set, req)
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
      abstract_dist = self._get_abstract_dist_for(req_to_install)
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
      req, self.session, self.finder, self.require_hashes
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
      req, self.req_tracker, finder, self.build_isolation,
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
      abstract_dist.prepare_distribution_metadata(finder, build_isolation)
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
      self._setup_isolation(finder)
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
      reqs = backend.get_requires_for_build_wheel()
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
      'config_settings': config_settings
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
      raise BackendUnavailable(data.get('traceback', ''))
  pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
      obj = import_module(mod_path)
    File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'flit_core'
  
  ----------------------------------------
ERROR: Command errored out with exit status 2: /tmp/tmp.T3P0i9HVs6/.env/bin/python3.7 /tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /run/user/1000/pip-build-env-1pf2pow0/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'flit_core >=2.0.2,<3' Check the logs for full command output.
```

It looks like `flit_core` is the culprit here, so I tested it specifically:

```
[sebastian@librem:/tmp/tmp.T3P0i9HVs6]$ pip download flit_core --no-binary :all:
Collecting flit_core
  Using cached https://files.pythonhosted.org/packages/89/cf/a76f37dfded167e97936b8d53308abe5a8d00b97d417a6a405e69167e685/flit_core-2.0.2.tar.gz
  Saved ./flit_core-2.0.2.tar.gz
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/commands/download.py", line 144, in run
    resolver.resolve(requirement_set)
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/tmp/tmp.T3P0i9HVs6/.env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flit_core'
```

As you can see from the error output, pip throws a `BackendUnavailable` exception.  I guess there is a disconnect between what `pip` expects from `pyproject.toml` and what is provided by `flit_core`.

**Comment by takluyver** [comment]
pip needs a change to support the `backend-path` option flit_core uses to bootstrap itself:
https://github.com/pypa/pip/pull/7394

Until that's merged and released, the workaround is to let it install `flit_core` as a wheel.
