### ISSUE TITLE
__version__ detection crashes on certain files

### ISSUE THREAD

**Issue by mands** [takluyver/flit#343]
I've noticed that flit fails to detect the `__version__` field correctly in certain files due to the ast parsing logic. For instance, building the following project raises an `AttributeError` in `flit_core.common.get_docstring_and_version_via_ast`

#### pyproject.toml
```toml
[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "flittest"
author = "mands"
author-email = "mands@example.com"
```

#### flittest.py

```python
"""docstring"""

a = {}
a["test"] = 3

__version__ = "0.0.1"

if __name__ == "__main__":
   print("hello")
```

#### flit build
```python
Traceback (most recent call last):
  File "/home/mands/.local/bin/flit", line 8, in <module>
    sys.exit(main())
  File "/home/mands/.local/lib/python3.8/site-packages/flit/__init__.py", line 170, in main
    main(args.ini_file, formats=set(args.format or []),
  File "/home/mands/.local/lib/python3.8/site-packages/flit/build.py", line 45, in main
    sb = SdistBuilder.from_ini_path(ini_file)
  File "/home/mands/.local/lib/python3.8/site-packages/flit/sdist.py", line 145, in from_ini_path
    return super().from_ini_path(str(ini_path))
  File "/home/mands/.local/lib/python3.8/site-packages/flit_core/sdist.py", line 102, in from_ini_path
    metadata = common.make_metadata(module, ini_info)
  File "/home/mands/.local/lib/python3.8/site-packages/flit_core/common.py", line 368, in make_metadata
    md_dict.update(get_info_from_module(module))
  File "/home/mands/.local/lib/python3.8/site-packages/flit_core/common.py", line 178, in get_info_from_module
    docstring, version = get_docstring_and_version_via_ast(target)
  File "/home/mands/.local/lib/python3.8/site-packages/flit_core/common.py", line 133, in get_docstring_and_version_via_ast
    child.targets[0].id == "__version__" and
AttributeError: 'Subscript' object has no attribute 'id'
```

Potentially a bit of an odd-case, but I have to automate conversion of such files often and often append the version to existing files to get them to build with flit. 

Related - it would be great if we could optionally specify the version field in the `pyproject.toml` file and skip looking in the code in those cases.

**Comment by takluyver** [comment]
Thanks, good point.

There's discussion underway to define a standard for putting metadata in `pyproject.toml` - that will likely include an optional version field, and if it's set then flit will respect it.

**Comment by mands** [comment]
Sounds great - yes an optional version field would be incredibly useful.

**Comment by takluyver** [comment]
#348 fixes the error in the simple test case. Do you want to try it on the real case where you discovered this?
