### ISSUE TITLE
USER_SITE may not exist.

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#4]
Which is weird, but 
```
Symlinking flit -> /Users/bussonniermatthias/Library/Python/3.5/lib/python/site-packages/flit  I-flit.install
Traceback (most recent call last):
  File "/usr/local/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flit/__init__.py", line 191, in main
    Installer(pkg, symlink=args.symlink).install()
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flit/install.py", line 97, in install
    os.symlink(str(self.module.path.resolve()), dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bussonniermatthias/dev/flit/flit' -> '/Users/bussonniermatthias/Library/Python/3.5/lib/python/site-packages/flit'
```

But that might be because I'm on 3.5a1

**Comment by takluyver** [comment]
Is it the first thing you've installed into USER_SITE with 3.5? I could imagine that the directory isn't created until you put something there.

**Comment by Carreau** [comment]
Yep. I never install --user as 3.5 has already a brew prefix writable I can nuke without questions. So at first I even thought it was a bug it making the path.
