### ISSUE TITLE
FileNotFoundError when running build or publish

### ISSUE THREAD

**Issue by fanoway** [takluyver/flit#418]
There are no errors when using the init or install commands bunning build or install returns the following error:

```C:\Users\User Name\Downloads\entrypoint>pipenv run flit build
Traceback (most recent call last):
  File "c:\users\user name\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user name\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\eser name\.virtualenvs\entrypoint-RYMZNUJV\Scripts\flit.exe\__main__.py", line 7, in <module>
  File "c:\users\user name\.virtualenvs\entrypoint-rymznujv\lib\site-packages\flit\__init__.py", line 154, in main
    main(args.ini_file, formats=set(args.format or []),
  File "c:\users\user name\.virtualenvs\entrypoint-rymznujv\lib\site-packages\flit\build.py", line 46, in main
    sdist_file = sb.build(dist_dir, gen_setup_py=gen_setup_py)
  File "c:\users\user name\.virtualenvs\entrypoint-rymznujv\lib\site-packages\flit_core\sdist.py", line 182, in build
    files_to_add = self.apply_includes_excludes(self.select_files())
  File "c:\users\user name\.virtualenvs\entrypoint-rymznujv\lib\site-packages\flit\sdist.py", line 146, in select_files
    untracked_deleted = vcs_mod.list_untracked_deleted_files(self.cfgdir)
  File "c:\users\user name\.virtualenvs\entrypoint-rymznujv\lib\site-packages\flit\vcs\git.py", line 12, in list_untracked_deleted_files
    outb = check_output(['git', 'ls-files', '--deleted', '--others',
  File "c:\users\user name\appdata\local\programs\python\python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\users\user name\appdata\local\programs\python\python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\user name\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\user name\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified```

**Comment by fanoway** [comment]
I have found the source of the error.  flit\vcs\git.py is looking for for the git folder. while it should be looking for .git. Created a pull request to resovle

**Comment by takluyver** [comment]
This looks like it's not finding the `git` command. Flit assumes that if you're using a Git repository, the `git` command will be on PATH. That's a pretty easy assumption to make on Linux & Mac systems, maybe not quite so much on Windows. You may need to select some option when you install git, or run flit from inside the special git command prompt.

**Comment by fanoway** [comment]
I’ll give that a go, when I renamed the .git to just git it seemed to work.
But I didn’t do extensive testing
