### ISSUE TITLE
Trouble uploading to test repository KeyError: 'testpypi'

### ISSUE THREAD

**Issue by sgbaird** [takluyver/flit#455]
I installed via [conda-forge](https://anaconda.org/conda-forge/flit):
```python
conda install -c conda-forge flit
```

I'm running in VS Code on Windows. The directory structure is as follows:
<img src=https://user-images.githubusercontent.com/45469701/137440102-90076df5-1f95-492f-8fe9-faf5cc650f16.png width=200>

My `C:\Users\sterg\.pypirc` is as follows:
```python
[pypi]
username = __token__
password = <password-removed>

[testpypi]
  username = __token__
  password = <password-removed>
```
The error is as follows:
```python
(packaging_tutorial) C:\Users\sterg\Documents\GitHub\sparks-baird\packaging_tutorial>flit publish --repository testpypi
Adding generated setup.py to sdist by default.                  I-flit
This will change in a future version. Pass --[no-]setup-py to control it.  I-flit
Found 7 files tracked in git                              I-flit.sdist
Writing generated setup.py                                I-flit.sdist
Built sdist: dist\example_package_sparks_baird-1.0.0.tar.gz  I-flit_core.sdist
Copying package file(s) from C:\Users\sterg\AppData\Local\Temp\tmp30k84nba\example_package_sparks_baird-1.0.0\src\example_package_sparks_baird  I-flit_core.wheel
Writing metadata files                               I-flit_core.wheel
Writing the record of files                          I-flit_core.wheel
Built wheel: dist\example_package_sparks_baird-1.0.0-py2.py3-none-any.whl  I-flit_core.wheel
Traceback (most recent call last):
  File "C:\Users\sterg\anaconda3\envs\packaging_tutorial\Scripts\flit-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\sterg\anaconda3\envs\packaging_tutorial\lib\site-packages\flit\__init__.py", line 191, in main
    main(args.ini_file, repository, args.pypirc, formats=set(args.format or []),
  File "C:\Users\sterg\anaconda3\envs\packaging_tutorial\lib\site-packages\flit\upload.py", line 268, in main
    do_upload(built.wheel.file, built.wheel.builder.metadata, pypirc_path, repo_name)
  File "C:\Users\sterg\anaconda3\envs\packaging_tutorial\lib\site-packages\flit\upload.py", line 245, in do_upload        
    repo = get_repository(pypirc_path, repo_name)
  File "C:\Users\sterg\anaconda3\envs\packaging_tutorial\lib\site-packages\flit\upload.py", line 93, in get_repository    
    repo = repos_cfg[name]
KeyError: 'testpypi'
```

Uploading directly to PyPi works fine, however:
```python
(packaging_tutorial) C:\Users\sterg\Documents\GitHub\sparks-baird\packaging_tutorial>flit publish
Adding generated setup.py to sdist by default.                  I-flit
This will change in a future version. Pass --[no-]setup-py to control it.  I-flit
Found 7 files tracked in git                              I-flit.sdist
Writing generated setup.py                                I-flit.sdist
Built sdist: dist\example_package_sparks_baird-1.0.0.tar.gz  I-flit_core.sdist
Copying package file(s) from C:\Users\sterg\AppData\Local\Temp\tmpo9adksta\example_package_sparks_baird-1.0.0\src\example_package_sparks_baird  I-flit_core.wheel
Writing metadata files                               I-flit_core.wheel
Writing the record of files                          I-flit_core.wheel
Built wheel: dist\example_package_sparks_baird-1.0.0-py2.py3-none-any.whl  I-flit_core.wheel
Using repository at https://upload.pypi.org/legacy/      I-flit.upload
Uploading dist\example_package_sparks_baird-1.0.0-py2.py3-none-any.whl...  I-flit.upload
Package is at https://pypi.org/project/example_package_sparks_baird/  I-flit.upload
Using repository at https://upload.pypi.org/legacy/      I-flit.upload
Uploading dist\example_package_sparks_baird-1.0.0.tar.gz...  I-flit.upload
Package is at https://pypi.org/project/example_package_sparks_baird/  I-flit.upload
```

**Comment by takluyver** [comment]
I've also considered special casing testpypi, like Flit already does for PyPI - see #125 for that.
