### ISSUE TITLE
Editable installs with src in 3.5.0

### ISSUE THREAD

**Issue by bollwyvl** [takluyver/flit#471]
Thanks for `flit`, and congrats on 3.5.0!

Using a `src/<module>/__init__.py` layout, I am, however, seeing some odd behavior with editable installs on `flit(-core) 3.5.0`:

### `flint install --symlink --deps=none`
```
Symlinking src/jupyterlite -> ~/envs/default/lib/python3.9/site-packages/src/jupyterlite  I-flit.install
Traceback (most recent call last):
  File "~/envs/default/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "~/envs/default/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "~/envs/default/lib/python3.9/site-packages/flit/__main__.py", line 5, in <module>
    main()
  File "~/envs/default/lib/python3.9/site-packages/flit/__init__.py", line 200, in main
    Installer.from_ini_path(args.ini_file, user=args.user, python=python,
  File "~/envs/default/lib/python3.9/site-packages/flit/install.py", line 416, in install
    self.install_directly()
  File "~/envs/default/lib/python3.9/site-packages/flit/install.py", line 312, in install_directly
    os.symlink(src.resolve(), dst)
FileNotFoundError: [Errno 2] No such file or directory: '~/jupyterlite/py/jupyterlite/src/jupyterlite' -> '~/envs/default/lib/python3.9/site-packages/src/jupyterlite'

```
  - presumably failing because `site-packages/src` does not exist

### `flit install --pth-file --deps=none`
```
Adding .pth file ~/envs/default/lib/python3.9/site-packages/jupyterlite.pth for src  I-flit.install
Writing script to ~/envs/default/bin/jupyter-lite  I-flit.install
```
- just exhibits `no module named jupyterlite` when importing, running CLI, etc.

Meanwhile... reverting to `flit 3.4.0` does not have this issue:

```
Symlinking src/jupyterlite -> ~/envs/default/lib/python3.9/site-packages/jupyterlite  I-flit.install
Writing script to ~/envs/default/bin/jupyter-lite  I-flit.install
```

```
Adding .pth file ~/envs/default/lib/python3.9/site-packages/jupyterlite.pth for ~/jupyterlite/py/jupyterlite/src  I-flit.install
Writing script to ~/envs/default/bin/jupyter-lite  I-flit.install
```

**Comment by takluyver** [comment]
Sorry about that. It will be the changes in #468 that broke it.

**Comment by takluyver** [comment]
#472 should fix this.

**Comment by bollwyvl** [comment]
Fantastic turn-around, thanks!

**Comment by bollwyvl** [comment]
Hooray?

**Comment by takluyver** [comment]
I hope so: 3.5.1 is out now and should fix this. Feel free to open a new issue, or comment here, if there are still problems.

**Comment by bollwyvl** [comment]
Sounds great, and thanks again. My CI will be testing it out as soon as https://github.com/conda-forge/flit-feedstock/pull/32 lands! It's great to see `src` under test, going forward.

**Comment by bollwyvl** [comment]
(actually, will be testing the PyPI version before that, locally)
