### ISSUE TITLE
Pypi seem to have change python-requires format '3' not valid

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#84]
```
Traceback (most recent call last):
  File "/Users/bussonniermatthias/.local/bin/flit", line 4, in <module>
    main()
  File "/Users/bussonniermatthias/.local/lib/python3.5/site-packages/flit/__init__.py", line 88, in main
    repo=args.repository)
  File "/Users/bussonniermatthias/.local/lib/python3.5/site-packages/flit/wheel.py", line 191, in wheel_main
    do_upload(wheel_path, wb.metadata, repo)
  File "/Users/bussonniermatthias/.local/lib/python3.5/site-packages/flit/upload.py", line 164, in do_upload
    upload_wheel(file, metadata, repo)
  File "/Users/bussonniermatthias/.local/lib/python3.5/site-packages/flit/upload.py", line 133, in upload_wheel
    resp.raise_for_status()
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: requires_python: Invalid specifier in requirement. for url: https://upload.pypi.io/legacy/
```

See https://github.com/Carreau/warn/blob/8fbb2e0a4e8c46f88361ae3d690784444cc8ca5c/flit.ini  and previous commit (uploading through warehouse)

I should likely check whether it's a warehouse thing but I want to make sure to fix flit docs if it's not the case.

**Comment by takluyver** [comment]
The examples at https://www.python.org/dev/peps/pep-0345/#version-specifiers seem to show that a version specifier consisting of just a number is fine, and that `3` is a shorthand for `>=3,<4`. So I think we should try making an issue on Warehouse for it. They may say that the PEP should be changed, or that Warehouse is going to be more restrictive than the metadata spec, in which case we can handle that.

**Comment by takluyver** [comment]
You've updated the docs, but I'll leave this open for now because it would also be good for flit to check this, so you can discover the problem before attempting to upload to warehouse.

**Comment by takluyver** [comment]
Validation added in #154.
