### ISSUE TITLE
ImportError: No module named 'cv2'

### ISSUE THREAD

**Issue by N2ITN** [takluyver/flit#95]
The python bindings for opencv are created via `apt-get install python-opencv`, and so I'm guessing flit can't find them.  cv2 is installed and works with python. 

Is there a way to still build my package without digging into flit and making exceptions for this package? Maybe there is a way to add include it in the paths that flit checks?

```
$ flit wheel --upload
installing system dependencies
Traceback (most recent call last):
  File "/usr/local/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/flit/__init__.py", line 88, in main
    repo=args.repository)
  File "/usr/local/lib/python3.4/dist-packages/flit/wheel.py", line 197, in wheel_main
    wb = WheelBuilder(ini_path, fp)
  File "/usr/local/lib/python3.4/dist-packages/flit/wheel.py", line 44, in __init__
    self.metadata = common.make_metadata(self.module, self.ini_info)
  File "/usr/local/lib/python3.4/dist-packages/flit/common.py", line 228, in make_metadata
    md_dict.update(get_info_from_module(module))
  File "/usr/local/lib/python3.4/dist-packages/flit/common.py", line 78, in get_info_from_module
    m = sl.load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "RPiViz/__init__.py", line 5, in <module>
    from RPiViz import deps, do_magic, executor, identify
  File "RPiViz/do_magic.py", line 2, in <module>
    import cv2
ImportError: No module named 'cv2'
```

Cheers

**Comment by N2ITN** [comment]
It's not flit, so much as the use of importlib.machinery.SourceFileLoader that's throwing the error.

**Comment by takluyver** [comment]
The `python-opencv` package in Ubuntu is for Python 2; flit runs on Python 3, so it won't find that.

Your package needs to be importable in Python 3 for flit to package it. You can work around this by adjusting what gets imported at the top level, so that `import RPiViz` by itself doesn't cause cv2 to be loaded.

**Comment by N2ITN** [comment]
Changed 'import RpiViz' to '__all__ = ['executor']', and it worked.

Thanks!
